title: Test Blog
description: Your blog description

baseurl: ""
url: "https://krugsec.blog"

# Theme settings
theme: jekyll-theme-console

# Console theme header pages (these will show as links)
header_pages:
  - index.md
  - about.md

# Style (dark or light)
style: dark

# Footer text
footer_right: 'Follow me on <a href="https://github.com/smnkrgr">GitHub</a>'
footer_left: '<a href="/privacy-policy/">Privacy Policy</a>'

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
